ORM/WeddingPlanner/Controllers/PlannerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Contexts;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace WeddingPlanner.Controllers
{
    [Route("weddingplanner")]
    public class PlannerController : Controller
    {
        private HomeContext dbContext;
        public PlannerController(HomeContext context)
        {
            dbContext = context;
        }

        [HttpGet("dashboard")]
        public IActionResult Index()
        {
            User dbUser = LoggedIn();
            if(dbUser == null)
            {
                return RedirectToAction("Logout", "Home");
            }
            ViewBag.User = dbUser;
            List<Wedding> AllWeddings = dbContext.Weddings.Include(w => w.Guests).ThenInclude(a => a.Guest).Include(w => w.Creator).ToList();
            return View(AllWeddings);
        }

        [HttpGet("wedding/new")]
        public IActionResult NewWedding()
        {
            return View();
        }

        [HttpPost("wedding/new/create")]
        public IActionResult Create(Wedding newWedding)
        {
            User dbUser = LoggedIn();
            if(dbUser == null)
            {
                return RedirectToAction("Logout", "Home");
            }
            if(ModelState.IsValid)
            {
                User current = dbContext.Users.Include(u => u.PlannedWeddings).FirstOrDefault(u => u.UserId == dbUser.UserId);
                current.PlannedWeddings.Add(newWedding);
                dbContext.Weddings.Add(newWedding);
                dbContext.SaveChanges();
                return Redirect($"/weddingplanner/wedding/{newWedding.WeddingId}");
            }
            else
            {
                return View("NewWedding");
            }
        }

        [HttpGet("wedding/{weddingId}")]
        public IActionResult WeddingInfo(int weddingId)
        {
            Wedding dbWedding = dbContext.Weddings.Include(w => w.Guests).ThenInclude(a => a.Guest).FirstOrDefault(w => w.WeddingId == weddingId);
            ViewBag.Guests = dbWedding.Guests.ToList();
            ViewBag.Wedding = dbWedding;
            return View();
        }

        [HttpGet("wedding/{weddingId}/rsvp")]
        public IActionResult RSVP(int weddingId)
        {
            User dbUser = LoggedIn();
            if(dbUser == null)
            {
                return RedirectToAction("Logout", "Home");
            }
            Association newAssoc = new Association();
            newAssoc.Guest = dbUser;
            newAssoc.Wedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);
            dbContext.Associations.Add(newAssoc);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet("wedding/{weddingId}/unrsvp")]
        public IActionResult UNRSVP(int weddingId)
        {
            User dbUser = LoggedIn();
            if(dbUser == null)
            {
                return RedirectToAction("Logout", "Home");
            }
            Association dbAssoc = dbContext.Associations.FirstOrDefault(a => a.WeddingId == weddingId);
            dbContext.Associations.Remove(dbAssoc);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet("wedding/{weddingId}/delete")]
        public IActionResult Delete(int weddingId)
        {
            Wedding dbWedding = dbContext.Weddings.SingleOrDefault(w => w.WeddingId == weddingId);
            List<Association> associations = dbContext.Associations.Where(a => a.WeddingId == weddingId).ToList();
            foreach(var item in associations)
            {
                dbContext.Associations.Remove(item);
            }
            dbContext.Weddings.Remove(dbWedding);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        private User LoggedIn()
        {
            return dbContext.Users.Include(u => u.Weddings).ThenInclude(a => a.Wedding).FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));
        }
    }


}

ORM/WeddingPlanner/Views/Planner/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

@model List<Wedding>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-action="Index" asp-controller="Planner">Dashboard</a>
    <a class="navbar-brand" asp-action="Logout" asp-controller="Home">Logout</a>
</nav>

<br><h2>Hi, @ViewBag.User.FirstName!</h2><br>

<div class="text-center">
    <h3>Weddings list:</h3><br>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Wedding</th>
                <th scope="col">Date</th>
                <th scope="col"># of Guests</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var wedding in Model)
            {
                <tr>
                    <td><a asp-action="WeddingInfo" asp-route-weddingId="@wedding.WeddingId" asp-controller="Planner">@wedding.WedderOne & @wedding.WedderTwo</a></td>
                    <td>@wedding.Date.ToString("MMM dd, yyyy")</td>
                    <td>@wedding.Guests.Count</td>
                    <td>
                        @if(ViewBag.User.UserId == wedding.Creator.UserId)
                        {
                            <a asp-action="Delete" asp-route-weddingId="@wedding.WeddingId" asp-controller="Planner">Delete</a>
                        }
                        else
                        {
                            if(wedding.Guests.Any( g => g.UserId == ViewBag.User.UserId ))
                            {
                                <a asp-action="UNRSVP" asp-route-weddingId="@wedding.WeddingId" asp-controller="Planner">Un-Rsvp</a>
                            }
                            if(wedding.Guests.All( g => g.UserId != ViewBag.User.UserId ))
                            {
                                <a asp-action="RSVP" asp-route-weddingId="@wedding.WeddingId" asp-controller="Planner">Rsvp</a>
                            }
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-danger" asp-action="NewWedding" asp-controller="Planner">New Wedding</a>
</div>

ORM/WeddingPlanner/Views/Planner/NewWedding.cshtml
@model Wedding

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-action="Index" asp-controller="Planner">Dashboard</a>
    <a class="navbar-brand" asp-action="Logout" asp-controller="Home">Logout</a>
</nav>

<br><h2>Plan your wedding:</h2><br>

<div class="text-center">
    <form class="col-5" asp-action="Create" asp-controller="Planner" method="post">
        <div class="form-group">
            <span class="validation" asp-validation-for="WedderOne"></span><br>
            <label asp-for="WedderOne"></label>
            <input class="form-control" asp-for="WedderOne">
        </div>
        <div class="form-group">
            <span class="validation" asp-validation-for="WedderTwo"></span><br>
            <label asp-for="WedderTwo"></label>
            <input class="form-control" asp-for="WedderTwo">
        </div>
        <div class="form-group">
            <span class="validation" asp-validation-for="Date"></span><br>
            <label asp-for="Date"></label>
            <input class="form-control" asp-for="Date">
        </div>
        <div class="form-group">
            <span class="validation" asp-validation-for="Address"></span><br>
            <label asp-for="Address"></label>
            <input class="form-control" asp-for="Address">
        </div>
        <input class="btn btn-danger" type="submit" value="Create">
    </form>

</div>

ORM/WeddingPlanner/Views/Planner/WeddingInfo.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-action="Index" asp-controller="Planner">Dashboard</a>
    <a class="navbar-brand" asp-action="Logout" asp-controller="Home">Logout</a>
</nav>

<br><h2>@ViewBag.Wedding.WedderOne & @ViewBag.Wedding.WedderTwo's Wedding</h2><br>

<h4>Date: @ViewBag.Wedding.Date.ToString("MMM dd, yyyy")</h4><br>

<h4>Guests:</h4>

<ul class="list-group list-group-flush">
    @foreach(var guest in ViewBag.Guests)
    {
        <li class="list-group-item">@guest.Guest.FirstName @guest.Guest.LastName</li>
    }
</ul>